### ISSUE TITLE
Simplify or not the outputs of the converter

### ISSUE THREAD

**Issue by floradanna** [ELIXIR-Belgium/DMPConverter#3]
Currently, our converter try to re-create the exact layout of every funder's template (such as the 2 columns table with blue and grey headers for FWO etc...). However, it seems that this is not needed since funders accept DMP created on DMPonline, which doesn't not re-create funder's layout when exporting a DMP. So, I was wondering if could be better and easier for us to manage a template+converter with simpler layout.

Here there are examples of the layout of DMPs exported from DMPonline:
[ERC_DMPonline_export.pdf](https://github.com/ELIXIR-Belgium/DMPConverter/files/5797259/ERC_DMPonline_export.pdf)
[FWO_DMPonline_export.pdf](https://github.com/ELIXIR-Belgium/DMPConverter/files/5797260/FWO_DMPonline_export.pdf)
[H2020_DMPonline_export.pdf](https://github.com/ELIXIR-Belgium/DMPConverter/files/5797261/H2020_DMPonline_export.pdf)

**Comment by floradanna** [comment]
To be decided after checking what layout is accepted by funders (@lsterck, @rabuono)

**Comment by vdkkia** [comment]
A new simple template is being used now.
